#!/bin/sh

setxkbmap dvorak
xrdb ~/.Xresources

hsetroot -solid "#3a3a3a"
unclutter --timeout 2 &

mkdir /tmp /tmp/nowm

emacs --daemon

dunst &
~/.wm/bar.sh | lemonbar -pd -f 'Liberation Mono' &
wew | ~/.wm/watch.sh &
exec sxhkd
